baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Dubai Massage"

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

buildDrafts = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
