baseurl = "https://www.dubaierotic.com"
languageCode = "en-us"
languageLang = "en"
title = "Dubai Erotic"

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

buildDrafts = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
