baseurl = "https://sina.dubaierotic.com/"
title = "Sina Dubai Massage"
languageCode = "en-us"
languageLang = "en"
enableEmoji = true
googleAnalytics = "UA-126190930-1"

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[blackfriday]
  backslashLineBreak = true
  spaceHeaders = false
  hrefTargetBlank = false
  angledQuotes = true
  latexDashes = false
  extensions = ["laxHtmlBlocks"]

[menu]

  [[menu.global]]
    identifier = "home"
    name = "Home"
    pre = "<span class='uk-margin-small-right' uk-icon='icon:home'></span>"
    url = "#home"
    weight = 100

  [[menu.global]]
    identifier = "gallery"
    name = "Gallery"
    pre = "<span class='uk-margin-small-right' uk-icon='icon:image'></span>"
    url = "#gallery"
    weight = 110

  [[menu.global]]
    identifier = "infos"
    name = "Infos"
    pre = "<span class='uk-margin-small-right' uk-icon='icon:heart'></span>"
    url = "#infos"
    weight = 120

  [[menu.global]]
    identifier = "prices"
    name = "Prices"
    pre = "<span class='uk-margin-small-right' uk-icon='icon:heart'></span>"
    url = "#prices"
    weight = 130

  [[menu.global]]
    identifier = "contact"
    name = "Contact"
    pre = "<span class='uk-margin-small-right' uk-icon='icon:user'></span>"
    url = "#contact"
    weight = 140

[params]
  artist = "Sina"
  land = "Vietnam"
  twitter = "@charmingsina"
