baseurl = "/"
title = "Sina Dubai Massage"
languageCode = "en-us"
languageLang = "en"

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

buildDrafts = true
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true